export class BuildingPersonRequiringAssistanceData {
  public data: any[] = [
    {
      'id': '1',
      'idBuilding': '3',
      'idBuildingInformation': '3',
      'idPersonRequiringAssistanceType': 'd2a08be0-8779-4be3-8c4e-91ce421d2242',
      'dayResidentCount': 1,
      'eveningResidentCount': 3,
      'nightResidentCount': 2,
      'dayIsApproximate': false,
      'eveningIsApproximate': true,
      'nightIsApproximate': false,
      'description': 'Attention, c\'est chaud.',
      'praName': 'Garderie le Grand Pré',
      'floor': '1',
      'local': 'B2',
      'contactName': 'Conrad Darnoc',
      'contactPhoneNumber': '418-555-2938',
      'createdOn': '2017-05-02 10:59:03',
      'isActive': true
    },
    {
      'id': '2',
      'idBuilding': '3',
      'idBuildingInformation': '3',
      'idPersonRequiringAssistanceType': 'd2a08be0-8779-4be3-8c4e-91ce421d2242',
      'dayResidentCount': 21,
      'eveningResidentCount': 23,
      'nightResidentCount': 22,
      'dayIsApproximate': true,
      'eveningIsApproximate': true,
      'nightIsApproximate': true,
      'description': 'Test #2',
      'praName': 'Conrad Darnoc',
      'floor': '1',
      'local': 'B1-N-60',
      'contactName': 'Conrad Darnoc',
      'contactPhoneNumber': '418-555-2938',
      'createdOn': '2017-05-02 10:59:03',
      'isActive': true
    },
    {
      'id': '3',
      'idBuilding': '3',
      'idBuildingInformation': '3',
      'idPersonRequiringAssistanceType': 'd2a08be0-8779-4be3-8c4e-91ce421d2242',
      'dayResidentCount': 6,
      'eveningResidentCount': 6,
      'nightResidentCount': 6,
      'dayIsApproximate': false,
      'eveningIsApproximate': false,
      'nightIsApproximate': false,
      'description': '',
      'praName': 'Test #3',
      'floor': '1',
      'local': 'B5',
      'contactName': 'Conrad Darnoc',
      'contactPhoneNumber': '418-555-2938',
      'createdOn': '2017-05-02 10:59:03',
      'isActive': true
    },
    {
      'id': '4',
      'idBuilding': '3',
      'idBuildingInformation': '3',
      'idPersonRequiringAssistanceType': 'd2a08be0-8779-4be3-8c4e-91ce421d2242',
      'dayResidentCount': 1,
      'eveningResidentCount': 1,
      'nightResidentCount': 1,
      'dayIsApproximate': true,
      'eveningIsApproximate': true,
      'nightIsApproximate': false,
      'description': 'Voici le test #4',
      'praName': 'Gilbert Brûlé',
      'floor': '2',
      'local': 'B4',
      'contactName': 'Conrad Darnoc',
      'contactPhoneNumber': '418-555-2938',
      'createdOn': '2017-05-02 10:59:03',
      'isActive': true
    }
  ];
}
